### ISSUE TITLE
Tag missing for version 1.7.0

### ISSUE THREAD

**Issue by djnym** [tsloughter/providers#10]
It seems to have been released (at least it's referenced in the .app.src and in the rebar3 rebar.config), but I don't see the tag.  @tsloughter ?

**Comment by djnym** [comment]
@tsloughter any thoughts on adding a tag?

**Comment by tsloughter** [comment]
Yea, I can tag it. Usually don't bother tagging since releases are just on hex.

**Comment by djnym** [comment]
@tsloughter  I don't use hex as I'm behind a firewall most of the time, so I mirror the code to our local github which is inside, then have systems build from that.  I end up replacing hex deps with git ones.  So tagging would be appreciated.

**Comment by djnym** [comment]
And since it's tagged, closing this.
